### ISSUE TITLE
No with clause supported in functions

### ISSUE THREAD

**Issue by tomvantilburg** [NLeSC/3D_geospatial_risk_management#18]
When creating a function with a with clause monetdb will complain about 'too many nested operators'.

**Comment by romulogoncalves** [comment]
Within a function, temporary tables are declared and then populated.
The WITH clause is to use in outside selections to define a temp table since there is not another for of doing it.

For example:

 DECLARE TABLE typesTable(
     type varchar(16) 
 );

 SET types = REPLACE(types,',',' ');
 INSERT into typesTable (type) SELECT \* FROM fTokenStringToTable(types);
